# Generated by Django 6.0.7 on 2026-08-14 09:55

import django.db.models.deletion
import exam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('points', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('manager', exam.models.StudentManager()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('answer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='exam.choice')),
                ('choices', models.ManyToManyField(related_query_name='questions', to='exam.choice')),
            ],
        ),
    ]
