# Generated by Django 6.0.7 on 2026-08-14 10:01

from django.db import migrations
from django.contrib.auth.models import User
from django.db import transaction
from exam.models import Question, Choice

def add_users(apps, schema_editor):
    if len(User.objects.all()) > 0:
        User.objects.all().delete()
    with transaction.atomic():
        User.objects.create_superuser(username="admin", email="admin@admin.example", password="thesuperboss")
        User.objects.create_user(username="seppo", password="smithingismylife")
        User.objects.create_user(username="onerva", password="letsplayhayday")

def add_questions(apps, schema_editor):
    if len(Question.objects.all()) > 0:
        Question.objects.all().delete()
    if len(Choice.objects.all()) > 0:
        Choice.objects.all().delete()
    with transaction.atomic():
        w = Choice.objects.create(choice_text="withers")
        q = Question.objects.create(question_text="What is the highest point of a horse's back called?", answer=w)
        c = q.choices.create(choice_text="croup")
        q.choices.create(choice_text="fetlock")
        m = q.choices.create(choice_text="muzzle")

        p = Choice.objects.create(choice_text="pastern")
        q = Question.objects.create(question_text="What is the part of a horse's leg called that connects the hoof and the fetlock?", answer=p)
        q.choices.add(c)
        q.choices.add(m)
        q.choices.create(choice_text="ergot")


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_users),
        migrations.RunPython(add_questions),
    ]
