# Generated by Django 6.0.7 on 2026-08-12 09:35

import django.db.models.deletion
import exam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_remove_choice_question_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('points', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('manager', exam.models.StudentManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(related_query_name='choices', to='exam.choice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='exam.choice'),
        ),
    ]
