# Generated by Django 6.0.7 on 2026-08-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_student_remove_choice_votes_question_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(related_query_name='questions', to='exam.choice'),
        ),
    ]
