# Generated by Django 6.0.7 on 2026-08-12 09:41

from django.db import migrations
from django.contrib.auth.models import User
from django.db import transaction

def add_users(apps, schema_editor):
    if len(User.objects.all()) > 0:
        User.objects.all().delete()
    with transaction.atomic():
        adminuser = User.objects.create_superuser(username="admin", email="admin@admin.example", password="thesuperboss")
        adminuser.save()
        user = User.objects.create_user(username="seppo", password="smithingismylife")
        user.save()
        user = User.objects.create_user(username="onerva", password="letsplayhayday")
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_alter_question_choices'),
    ]

    operations = [
        migrations.RunPython(add_users),
    ]